# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '13.0'
prepare_react_native_project!

# 👇 Remove this — it forces dynamic framework linking (which breaks clevertap-react-native)
# use_frameworks!

target 'ecommerceApp' do
  config = use_native_modules!

  # ✅ React Native + Static Framework patch for CleverTap
  pre_install do |installer|
    installer.pod_targets.each do |pod|
      if pod.name.eql?('clevertap-react-native')
        def pod.build_type; Pod::BuildType.static_library; end
      end
    end
  end

  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  pod 'clevertap-react-native', :path => '../node_modules/clevertap-react-native'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      if target.name == 'clevertap-react-native'
        target.build_configurations.each do |config|
          config.build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)', '-framework', 'CoreLocation']
        end
      end
    end
  end
end
