# Podfile

source 'https://github.com/CocoaPods/Specs.git'
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '17.0' # or 12.0 if you need older support

prepare_react_native_project!

# ✅ Static linking (solves UIKit/module issues in Xcode 15+)
use_frameworks! :linkage => :static


target 'NotificationContentDemo' do
  pod 'CTNotificationContent'
end
 
target 'NotificationCT' do
  pod 'CTNotificationService'
  pod 'CleverTap-iOS-SDK'
end

target 'ecommerceApp' do
  config = use_native_modules!
  $RNFirebaseAsStaticFramework = true # ✅ Enable Firebase static linking

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true, 
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # ✅ Modular headers for Firebase deps
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'Firebase', :modular_headers => true

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
